<a href="https://colab.research.google.com/github/Bae-SeungKwang/etc/blob/master/PythonBasic_%EB%B0%B0%EC%8A%B9%EA%B4%91_240330.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Numpy(Numerical Python) 기본: 배열과 벡터 연산

#numpy 기본 설정
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [3]:
#성능 차이를 확인하기 위해 백만개의 정수를 저장하는 Numpy 배열과 파이썬 리스트를 생성한다
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
#각각의 배열과 리스트 원소를 2배한 뒤 소요된 시간을 측정해본다
#1번만 돌리면 너무 빨리 끝나서 10번을 반복한 뒤 소요 시간을 측정하였다
%time for _ in range(10): my_arr = my_arr * 2
%time for _ in range(10): my_list = [x * 2 for x in my_list]
# 매트릭스를 사용한 결과가 빠름

CPU times: user 12.9 ms, sys: 10.1 ms, total: 23 ms
Wall time: 26.7 ms
CPU times: user 648 ms, sys: 206 ms, total: 854 ms
Wall time: 856 ms


In [6]:
#파이썬 내장 객체의 스칼라 값을 다루는 것과 유사한 방법으로 배치(한번에 대량)계산을 처리하는 방법을 알아보기
#우선 Numpy 패키지를 불러오고 임의의 값이 들어있는 작은 배열을 만들어 본다
import numpy as np
# 랜덤 숫자 생성. 2행 3열짜리 배열을 생성한 후 랜덤한 숫자를 넣는다
data1 = np.random.randn(2, 3) # -> Random + Normalization
data2 = np.random.rand(2,3)
print(data1)
print('-'*100)
print(data2)

[[-0.2047  0.4789 -0.5194]
 [-0.5557  1.9658  1.3934]]
----------------------------------------------------------------------------------------------------
[[0.9645 0.6532 0.7489]
 [0.6536 0.7477 0.9613]]


In [7]:
#생성된 배열에 들어있는 데이터를 산술연산 해본다
#아래의 예제는 배열의 모든 원소를 10배 한 것이다
data1 * 10

array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

In [8]:
#이제 배열의 모든 원소에 1을 더한다
#이런식으로 (배열 연산자 피연산자) 형식을 사용하면 배열의 모든 원소에 해당 연산자에 해당하는 연산이 적용된다
data1 + 1

array([[0.7953, 1.4789, 0.4806],
       [0.4443, 2.9658, 2.3934]])

In [9]:
# ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다.
# ndarray의 모든 원소는 같은 자료형이어야 한다. 모든 배열은 각 차원의 크기를 알려주는 shape라는 튜플과 배열
# data로 명명된 배열의 각 차원의 크기는 2행 3열이므로 (2,3), 배열에 저장된 자료형은 64비트 float 형태이다
print(data1.shape, data1.dtype)

(2, 3) float64


In [14]:
# 1.3 ndarray 생성하기
# 리스트(list): 파이썬의 기본 자료형으로 제공되는 리스트
# 배열(array): numpy에서 제공하는 고유 자료형 ndarray
# 배열(ndarray)을 생성하는 가장 쉬운 방법은 numpy의 array 함수를 이용하는 것이다.

# ndarray로 변환될 파이선의 기본 자료형인 리스트
data1 = [6,7.5,8,0,1]

# np.array(리스트) 형식으로 넣어주면 ndarray로 변경된다
arr1 = np.array(data1)

# arr1을 출력해보면 array[6,...] 형식으로 array라는 자료형으로 변경되었다는 안내문이 나온다
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
#같은 길이를 가지는 리스트를 포함하고 있는 순차 데이터는 다차원 배열로 변환 가능하다
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
# 2행 4열 형태의 배열로 전환되었다. 2행 4열이라는 형태는 그대로 유지된다
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
#numpy 배열은 ndim, shape 속성을 가지고 있다
#ndim 속성은 배열의 차원 수(row의 수)를 의미한다. arr2은 행이 2개이므로 2차원 배열이다.
#shape속성은 각 차원의 크기를 의미한다.차원의 크기란 다시 말하면 열의 개수와 같으므로 (행의 개수, 열의 개수)
print(arr2.ndim, arr2.shape)

2 (2, 4)


In [17]:
#dtype은 배열을 구성하는 데이터의 종류를 의미한다
#arr1은 64비트 float, arr2는 64비트 int로 구성되어 있다
print(arr1.dtype, arr2.dtype)

float64 int64


In [18]:
#numpy는 자주 쓰는 특이한 배열을 생성하기 위한 여러함수를 제공한다
#zeros 함수는 0으로만 이뤄진 배열을 생성한다. 아래의 코드는 10개의 0으로 이뤄진 배열을 생성한다
np.zeros(10)
#아래의 코드는 3행 6열 형태의 모든 원소가 0인 배열을 생성한다
np.zeros((3, 6))
#empty 함수는 초기화되지 않은 배열을 생성한다.
#아래의 코드는 3행 2열로 이뤄진 배열을 생성하되 초기화는 되지 않아 무작위 값이 들어있다
np.empty((3, 2))

array([[0.9645, 0.6532],
       [0.7489, 0.6536],
       [0.7477, 0.9613]])

In [20]:
#numpy에서 제공하는 arrange 함수는 파이썬의 range함수의 배열 버전이다(기능이 같다)
#아래는 0-14까지의 숫자를 웒소로 같은 배열을 생성하는 코드이다
print(list(range(15)))
print('-'*100)
np.arange(15)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
----------------------------------------------------------------------------------------------------


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
#ndarray의 astype 메서드를 사용하면 배열의 dtype을 다른 형으로 명시적으로 변경 가능하다
# 다른 프로그래밍 언어의 casting 기법과 동일한 기능이다
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
# 아래는 astype 메서드를 사용하여 int형 자료를 float64로 변경하고 있다
float_arr = arr.astype(np.float64)
float_arr.dtype

int64


dtype('float64')

In [23]:
#반대로 float 형 데이터를 int형으로 변경하는 것도 가능하다. 소수점 아래 값은 버려진다
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [25]:
#1.5 Numpy Array로 연산하기
#자기 자신과 곱하는 연산을 하면 곱 연산으로 전환된다
#[ 1 2 ] [ 1 2 ] = [ 1 4 ]
#  3 4     3 4       9 16

arr = np.array([[1,2], [3,4]])
arr*arr

array([[ 1,  4],
       [ 9, 16]])

In [27]:
#자기 자신과 더하는 연산을 하면 더하기 연산으로 전환된다
arr = np.array([[1,2], [3,4]])
arr+arr

array([[2, 4],
       [6, 8]])

In [28]:
# 1.6 색인과 슬라이싱 기초
#사용할 배열. 0부터 9까지의 정수가 들어있다
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#3차원 이상의 배열도 기존의 파이선의 3차원 이상의 리스트와 비슷하게 다루면 된다
#3차원 배열 생성. 2x2x3 크기의 배열이다
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
#arr3d[0]은 첫번째 2x3 배열을 의미한다
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#배열을 복사하려면 배열의 copy() 메소드를 사용한다
old_values = arr3d[0].copy()
print(old_values)
print('----------------------------')
#원본 배열을 일부 수정해본다
arr3d[0] = 0
print(arr3d)
print('----------------------------')
#다시 원상복구한다
arr3d[0] = old_values
print(arr3d)

[[1 2 3]
 [4 5 6]]
----------------------------
[[[ 0  0  0]
  [ 0  0  0]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
#아래의 출력 예시를 보면서 다차원 배열의 인덱스 사용법을 알아두면된다
print(arr3d)
print('----------------------------')
print(arr3d[1])
print('----------------------------')
print(arr3d[1][1])
print('----------------------------')
print(arr3d[1][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------------
[[ 7  8  9]
 [10 11 12]]
----------------------------
[10 11 12]
----------------------------
[7 8 9]


In [36]:
# 1.6.1 슬라이스로 선택하기
#아래에서 사용할 arr은 0-9까지의 숫자가 담겨 있다
arr = np.arange(10)
arr_slice = arr[:5]
print(arr)
print('----------------------------')
#0-5사이의 원소만 슬라이싱으로 가져온다
print(arr_slice)

[0 1 2 3 4 5 6 7 8 9]
----------------------------
[0 1 2 3 4]


In [40]:
# 1.6.2 불리안 값으로 선택하기
#중복된 이름이 포함된 배열이 있다
names = np.array(['Bae', 'Joe', 'Evan', 'Julian', 'Will', 'kim', 'kenneth', 'jamie'])

# names 배열에서 값이 'Bob'인것만 골라내기 (해당되면 True, 아니면 False 결과 출력)
names == 'Bob'

array([False, False, False, False, False, False, False, False])

In [42]:
# != 연산자는 같지 않음을 나타낸다
#이름이 'Bae'이 아닌 것
print(names[names != 'Bae'])
# ~ 연산자는 부정(반대)을 나타낸다
# 이름이 'Bob'인 것의 부정(이름이 'Bae'이 아닌 것)을 나타낸다
print(names[~(names=='Bae')])

['Joe' 'Evan' 'Julian' 'Will' 'kim' 'kenneth' 'jamie']
['Joe' 'Evan' 'Julian' 'Will' 'kim' 'kenneth' 'jamie']


In [43]:
#여러가지 조건을 동시에 사용하고 싶다면 &(and) 나 | (or) 같은 논리 연산자를 사용하면 된다
#이름이 'Bae'이거나 이름이 'kim'인 것만 골라냄
mask = (names == 'Bae') | (names == 'kim')
print('names =', names)
print('mask = ', mask)
print('------------------------')
print(names[mask])

names = ['Bae' 'Joe' 'Evan' 'Julian' 'Will' 'kim' 'kenneth' 'jamie']
mask =  [ True False False False False  True False False]
------------------------
['Bae' 'kim']


In [44]:
# 1이상 3미만의 숫자를 골라냄
arr= np.array([1,2,3,4,5])
print(arr)
mask = (arr>=1)&(arr<3)
print(arr[mask])

[1 2 3 4 5]
[1 2]
